name: PhantomPackets
author: JCThePants
main: PhantomPackets
version: 0.0-beta
depend: [NucleusFramework, ProtocolLib]
commands:
    phantom:
        description: Base command for PhantomPackets
        usage: |
            ERROR!
    phantompackets:
        description: Base command for PhantomPackets
        usage: |
            ERROR!
